CFLAGS		+= -I./sources/GUI/Inc
CPPFLAGS	+= -I./sources/GUI/Inc

CFLAGS		+= -I./sources/GUI
CPPFLAGS	+= -I./sources/GUI

VPATH += sources/GUI/Src
VPATH += sources/GUI

SOURCES_CPP += sources/GUI/gui_port.cpp

SOURCES_CPP += sources/GUI/Src/oled_gui.cpp
SOURCES_CPP += sources/GUI/Src/oled_obj.cpp
SOURCES_CPP += sources/GUI/Src/oled_anim.cpp

SOURCES_CPP += sources/GUI/Src/obj_bmp.cpp
SOURCES_CPP += sources/GUI/Src/obj_canvas.cpp
SOURCES_CPP += sources/GUI/Src/obj_group.cpp
SOURCES_CPP += sources/GUI/Src/obj_indicator.cpp
SOURCES_CPP += sources/GUI/Src/obj_label.cpp
SOURCES_CPP += sources/GUI/Src/obj_switch.cpp
