include sources/driver/Adafruit_ssd1306syp/Makefile
include sources/driver/button/Makefile
include sources/driver/buzzer/Makefile
include sources/driver/eeprom/Makefile


CFLAGS		+= -I./sources/driver
CPPFLAGS	+= -I./sources/driver

VPATH += sources/driver



