CFLAGS		+= -I./sources/application/tasks
CPPFLAGS	+= -I./sources/application/tasks

VPATH += sources/application/tasks

SOURCES_CPP += sources/application/tasks/task_gui.cpp
SOURCES_CPP += sources/application/tasks/task_scr.cpp
SOURCES_CPP += sources/application/tasks/task_button.cpp
SOURCES_CPP += sources/application/tasks/task_buzzer.cpp
SOURCES_CPP += sources/application/tasks/task_timer.cpp