CFLAGS		+= -I./sources/application/screens
CPPFLAGS	+= -I./sources/application/screens

VPATH += sources/application/screens
VPATH += sources/application/screens/Scr

SOURCES_CPP += sources/application/screens/scr_manager.cpp

SOURCES_CPP += sources/application/screens/Scr/scr_startup.cpp
SOURCES_CPP += sources/application/screens/Scr/scr_menu_game.cpp
SOURCES_CPP += sources/application/screens/Scr/scr_main_game.cpp
SOURCES_CPP += sources/application/screens/Scr/scr_setting_game.cpp
SOURCES_CPP += sources/application/screens/Scr/scr_chart_game.cpp