include sources/application/screens/Makefile
include sources/application/tasks/Makefile

CFLAGS		+= -I./sources/application
CPPFLAGS	+= -I./sources/application

VPATH += sources/application

SOURCES_CPP += sources/application/main.cpp
#SOURCES_CPP += sources/application/main_osc.cpp
#SOURCES_CPP += sources/application/main_example.cpp