CFLAGS += -I./sources/driver/nRF24
CPPFLAGS += -I./sources/driver/nRF24

VPATH += sources/driver/nRF24

SOURCES += sources/driver/nRF24/nrf24l01.c
SOURCES += sources/driver/nRF24/nrf24l01_low_level.c

