
CFLAGS		+= -I./sources/platform
CPPFLAGS	+= -I./sources/platform

VPATH += sources/platform

LDFILE = sources/platform/system_ls.ld
SOURCES += sources/platform/system_startup.c

#LDFILE = sources/platform/ak.ld
#SOURCES += sources/platform/system_copy.c

SOURCES += sources/platform/io_cfg.c
SOURCES += sources/platform/system.c
SOURCES += sources/platform/xprintf.c

